language: python
python:
  -   "2.7"
  -   "3.4"
  -   "3.5"
  -   "3.6"
  -   "3.7"
  -   "3.8"
  -   "3.9"
  -   "3.10"
dist: xenial
sudo: true

install:
  -   pip install pytest virtualenv
script:
  -   py.test -v tests
